# Generated by Django 4.2.5 on 2023-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('add_guests', models.IntegerField()),
                ('checkin', models.DateField(max_length=100)),
                ('checkout', models.DateField(max_length=100)),
                ('room_type', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
